from __future__ import annotations

from pathlib import Path
from typing import Protocol

from src.catalog_models import (
    ClientRecord,
    ContactRecord,
    OrganizationRecord,
    TemplateManifest,
    TemplateValidation,
)
from src.models import Attendee, MeetingMetadata, MinuteAnalysis


class MeetingRepository(Protocol):
    """Contrato común para SQLite y el futuro proveedor SQL Server."""

    def upsert_contact(self, attendee: Attendee) -> None: ...
    def list_contacts(self) -> list[Attendee]: ...
    def find_contact(self, name: str) -> Attendee | None: ...
    def upsert_contact_record(self, record: ContactRecord | dict) -> int: ...
    def list_contact_records(self, include_inactive: bool = False) -> list[dict]: ...
    def get_contact_record(self, contact_id: int | None) -> dict | None: ...
    def upsert_organization(self, record: OrganizationRecord | dict) -> int: ...
    def list_organizations(self, include_inactive: bool = False) -> list[dict]: ...
    def get_organization(self, organization_id: int | None) -> dict | None: ...
    def upsert_client(self, record: ClientRecord | dict) -> int: ...
    def list_clients(self, include_inactive: bool = False) -> list[dict]: ...
    def get_client(self, client_id: int | None) -> dict | None: ...
    def upsert_project(self, code: str, description: str | None, client: str | None) -> None: ...
    def list_projects(self) -> list[dict]: ...
    def get_project(self, code: str) -> dict | None: ...
    def upsert_project_profile(self, profile: dict) -> None: ...
    def set_record_active(self, table: str, record_id: int | str, active: bool) -> None: ...
    def set_project_members(self, project_code: str, names: list[str]) -> None: ...
    def list_project_members(self, project_code: str) -> list[Attendee]: ...
    def list_minute_numbers(self, project_code: str) -> list[str]: ...
    def find_meeting_by_source_sha256(self, sha256: str) -> dict | None: ...
    def dashboard_stats(self) -> dict[str, int]: ...
    def register_template_version(
        self,
        manifest: TemplateManifest,
        validation: TemplateValidation,
        file_path: str,
        sha256: str,
        state: str = "draft",
    ) -> int: ...
    def list_template_versions(self, include_retired: bool = True) -> list[dict]: ...
    def get_template_version(self, version_id: int | None) -> dict | None: ...
    def activate_template_version(self, version_id: int) -> None: ...
    def set_template_state(self, version_id: int, state: str) -> None: ...
    def resolve_template_version(
        self,
        project_code: str | None = None,
        meeting_type: str | None = None,
        default_template_key: str | None = None,
    ) -> dict | None: ...
    def log_audit(
        self,
        action: str,
        entity_type: str,
        entity_id: str | None,
        before: dict | None,
        after: dict | None,
        app_version: str | None = None,
    ) -> None: ...
    def list_audit_events(self, limit: int = 500) -> list[dict]: ...
    def integrity_check(self) -> tuple[bool, str]: ...
    def backup_to(self, destination: str | Path) -> Path: ...
    def get_schema_version(self) -> int: ...
    def move_meeting_to_trash(self, meeting_id: int, reason: str, trash_path: str | None, original_output_dir: str | None) -> None: ...
    def restore_meeting_from_trash(self, meeting_id: int, output_dir: str | None = None) -> None: ...
    def delete_meeting_permanently(self, meeting_id: int) -> None: ...
    def list_learning_examples(
        self,
        project_code: str | None = None,
        meeting_type: str | None = None,
        limit: int = 3,
    ) -> list[dict]: ...
    def save_meeting(
        self,
        metadata: MeetingMetadata,
        analysis: MinuteAnalysis | None,
        source_vtt: str,
        output_dir: str,
        model: str,
        status: str,
        docx_path: str | None = None,
        json_path: str | None = None,
        meeting_id: int | None = None,
        app_version: str | None = None,
        document_provider: str | None = None,
        processing_provider: str | None = None,
        processing_provider_name: str | None = None,
        last_error: str | None = None,
        source_type: str | None = None,
        source_quality: str | None = None,
        is_test: bool = False,
        template_version_id: int | None = None,
        template_key: str | None = None,
        template_version_label: str | None = None,
    ) -> int: ...
    def list_meetings(self, limit: int = 200, view: str = "active") -> list[dict]: ...
    def set_meeting_test(self, meeting_id: int, is_test: bool) -> None: ...
    def list_cleanup_candidates(self, limit: int = 200) -> list[dict]: ...
    def list_technical_terms(self, project_code: str | None = None) -> list[dict]: ...
    def record_correction_event(self, meeting_id: int | None, item_index: int | None, correction_type: str, before: dict | None, after: dict | None, approved_for_learning: bool = False) -> int: ...
    def register_learning_sample(self, meeting_id: int, approved: bool = True, anonymized: bool = False, approved_by: str | None = None) -> int: ...
    def get_meeting(self, meeting_id: int) -> dict | None: ...
